version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
          - 8080:80
        volumes:
          - ./src:/var/www
          - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
          - app
          - db

    app:
      container_name: avrora
      build: 
        context: ./php
        dockerfile: Dockerfile
      volumes:
        - ./src:/var/www
      ports:
        - "9000:9000"
      working_dir: /var/www

    db:
        image : mysql
        container_name : mysql
        volumes:
          - ./mysql/data:/var/lib/mysql
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: avrora_db
          MYSQL_ROOT_PASSWORD: root